import json
import os
import subprocess
import threading
import time

import telebot
from telebot import types

# IMPORTANT:
# Replace this with a NEW token generated by @BotFather.
TOKEN = "8724320555:AAF_Muv-Y3Resfstt8PxxnqwT_Cwac--Y14"

INITIAL_ADMIN_ID = "8173349543"

bot = telebot.TeleBot(TOKEN)

DATA_FILE = "users_data.json"
ADMINS_FILE = "admins.json"
CHANNELS_FILE = "channels.json"
USER_BOTS_DIR = "user_bots"

os.makedirs(USER_BOTS_DIR, exist_ok=True)

# Running user processes
active_user_processes = {}


TRANSLATIONS = {
    "dr": {
        "choose_lang": "لطفاً زبان خود را انتخاب کنید:",
        "welcome_menu": (
            "🌟 به ربات‌ساز تلگرامی خوش آمدید ✨\n\n"
            "🛠 لطفاً از منوی زیر استفاده کنید:"
        ),
        "profile": (
            "👤 پروفایل کاربری:\n\n"
            "⚡ نام: {name}\n"
            "📊 وضعیت ربات: {bot_status}\n"
            "🟢 امتیاز فعلی: {score}\n"
            "🆔 آیدی: {uid}\n"
            "🌐 لینک دعوت:\n{link}"
        ),
        "ref_bonus": "🎉 یک کاربر جدید با لینک دعوت شما وارد شد؛ ۵ امتیاز اضافه شد.",
        "support_prompt": "✍️ پیام خود را برای پشتیبانی ارسال کنید:",
        "support_sent": "✅ پیام شما برای پشتیبانی ارسال شد.",
        "join_lock": (
            "📢 برای استفاده از ربات، ابتدا در کانال‌های زیر عضو شوید:"
        ),
        "btn_check_join": "عضو شدم ✅ بررسی",
        "not_joined_alert": "❌ هنوز در تمام کانال‌ها عضو نشده‌اید.",
        "btn_online": "🛠 آنلاین کردن ربات",
        "btn_delete": "❌ حذف ربات",
        "btn_transfer": "🔄 انتقال امتیاز",
        "btn_buy": "🛒 خرید امتیاز",
        "btn_info": "✔ اطلاعات من",
        "btn_support": "✔ پشتیبانی",
    },
    "en": {
        "choose_lang": "Please choose your language:",
        "welcome_menu": "🌟 Welcome to the Telegram Bot Builder ✨\n\nUse the menu below:",
        "profile": (
            "👤 User Profile:\n\n"
            "⚡ Name: {name}\n"
            "📊 Bot Status: {bot_status}\n"
            "🟢 Score: {score}\n"
            "🆔 User ID: {uid}\n"
            "🌐 Referral link:\n{link}"
        ),
        "ref_bonus": "🎉 A new user joined through your referral link. 5 points added.",
        "support_prompt": "✍️ Send your message to support:",
        "support_sent": "✅ Your message was sent to support.",
        "join_lock": "📢 Please join the required channels first:",
        "btn_check_join": "Joined ✅ Check",
        "not_joined_alert": "❌ You have not joined all required channels.",
        "btn_online": "🛠 Online Bot",
        "btn_delete": "❌ Delete Bot",
        "btn_transfer": "🔄 Transfer Score",
        "btn_buy": "🛒 Buy Score",
        "btn_info": "✔ My Info",
        "btn_support": "✔ Support",
    },
}


def load_json(path, default):
    if not os.path.exists(path):
        return default
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"Could not load {path}: {e}")
        return default


def save_json(path, data):
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=4)
    os.replace(tmp, path)


def load_data():
    return load_json(DATA_FILE, {})


def save_data(data):
    save_json(DATA_FILE, data)


def load_admins():
    admins = [str(INITIAL_ADMIN_ID)]
    loaded = load_json(ADMINS_FILE, [])
    if isinstance(loaded, list):
        for aid in loaded:
            aid = str(aid)
            if aid not in admins:
                admins.append(aid)
    return admins


def save_admins(admins):
    unique = []
    for aid in [INITIAL_ADMIN_ID] + list(admins):
        aid = str(aid)
        if aid not in unique:
            unique.append(aid)
    save_json(ADMINS_FILE, unique)


def is_admin(user_id):
    return str(user_id) in load_admins()


def load_channels():
    default = [
        {
            "name": "@hackwhatandetc",
            "url": "https://t.me/hackwhatandetc",
            "id": "@hackwhatandetc",
        },
        {
            "name": "@hackwhatandetcb",
            "url": "https://t.me/hackwhatandetcb",
            "id": "@hackwhatandetcb",
        },
    ]

    if not os.path.exists(CHANNELS_FILE):
        save_json(CHANNELS_FILE, default)
        return default

    channels = load_json(CHANNELS_FILE, default)
    return channels if isinstance(channels, list) else default


def save_channels(channels):
    save_json(CHANNELS_FILE, channels)


def check_user_membership(user_id):
    channels = load_channels()

    for ch in channels:
        try:
            member = bot.get_chat_member(ch["id"], int(user_id))
            if member.status not in ("member", "administrator", "creator"):
                return False
        except Exception as e:
            print(f"Membership check failed for {ch['id']}: {e}")
            return False

    return True


def get_main_menu(lang="dr"):
    t = TRANSLATIONS.get(lang, TRANSLATIONS["dr"])
    markup = types.InlineKeyboardMarkup(row_width=2)

    markup.add(
        types.InlineKeyboardButton(t["btn_online"], callback_data="online_bot_menu"),
        types.InlineKeyboardButton(t["btn_delete"], callback_data="delete_bot_menu"),
        types.InlineKeyboardButton(t["btn_transfer"], callback_data="transfer_score_menu"),
        types.InlineKeyboardButton(t["btn_buy"], callback_data="buy_score_menu"),
        types.InlineKeyboardButton(t["btn_info"], callback_data="my_info"),
        types.InlineKeyboardButton(t["btn_support"], callback_data="support_btn"),
    )
    return markup


def send_main_menu(chat_id, lang="dr"):
    t = TRANSLATIONS.get(lang, TRANSLATIONS["dr"])
    bot.send_message(
        chat_id,
        t["welcome_menu"],
        reply_markup=get_main_menu(lang),
    )


def required_membership_message(chat_id, lang):
    channels = load_channels()
    markup = types.InlineKeyboardMarkup(row_width=1)

    for ch in channels:
        markup.add(types.InlineKeyboardButton(ch["name"], url=ch["url"]))

    markup.add(
        types.InlineKeyboardButton(
            TRANSLATIONS[lang]["btn_check_join"],
            callback_data="check_join",
        )
    )

    bot.send_message(
        chat_id,
        TRANSLATIONS[lang]["join_lock"],
        reply_markup=markup,
    )


def stop_process(bot_id):
    process = active_user_processes.pop(bot_id, None)
    if not process:
        return

    try:
        process.terminate()
        process.wait(timeout=5)
    except Exception:
        try:
            process.kill()
        except Exception:
            pass


def safe_bot_filename(name):
    name = os.path.splitext(name)[0]
    cleaned = "".join(c for c in name if c.isalnum() or c in "_-")
    return cleaned or "bot"


def check_code_syntax(path):
    try:
        with open(path, "r", encoding="utf-8") as f:
            code = f.read()
        compile(code, path, "exec")
        return True, None
    except Exception as e:
        return False, str(e)


def background_expiration_checker():
    while True:
        try:
            data = load_data()
            now = time.time()
            changed = False

            for uid, user_info in list(data.items()):
                bots = user_info.get("bots", {})

                for bot_id, bot_info in list(bots.items()):
                    expire_time = bot_info.get("expire_time")

                    if expire_time and now >= expire_time:
                        stop_process(bot_id)

                        path = os.path.join(
                            USER_BOTS_DIR,
                            f"{bot_id}_bot.py",
                        )

                        if os.path.exists(path):
                            try:
                                os.remove(path)
                            except Exception as e:
                                print(f"File delete error: {e}")

                        del bots[bot_id]
                        changed = True

                        try:
                            lang = user_info.get("lang") or "dr"
                            bot.send_message(
                                int(uid),
                                "⏳ مدت زمان ربات شما به پایان رسید و ربات خاموش شد."
                                if lang != "en"
                                else "⏳ Your bot activation time has expired.",
                            )
                        except Exception:
                            pass

            if changed:
                save_data(data)

        except Exception as e:
            print(f"Expiration checker error: {e}")

        time.sleep(60)


@bot.message_handler(commands=["start"])
def start(message):
    uid = str(message.from_user.id)
    data = load_data()

    args = message.text.split()
    is_new = uid not in data

    if is_new:
        data[uid] = {
            "score": 0,
            "lang": None,
            "bots": {},
        }

        if len(args) > 1:
            referrer = args[1]

            if referrer in data and referrer != uid:
                data[referrer]["score"] = data[referrer].get("score", 0) + 5

                try:
                    ref_lang = data[referrer].get("lang") or "dr"
                    bot.send_message(
                        int(referrer),
                        TRANSLATIONS[ref_lang]["ref_bonus"],
                    )
                except Exception:
                    pass

        save_data(data)

        # Notify admins about a new user.
        for admin_id in load_admins():
            try:
                username = (
                    f"@{message.from_user.username}"
                    if message.from_user.username
                    else "ندارد"
                )

                text = (
                    "👤 کاربر جدید\n\n"
                    f"⚡ نام: {message.from_user.first_name or 'بدون نام'}\n"
                    f"🔗 یوزرنیم: {username}\n"
                    f"🆔 UserID: {uid}"
                )

                bot.send_message(int(admin_id), text)
            except Exception:
                pass

    if data[uid].get("lang") is None:
        markup = types.InlineKeyboardMarkup(row_width=2)
        markup.add(
            types.InlineKeyboardButton("دری 🇦🇫", callback_data="lang_dr"),
            types.InlineKeyboardButton("English 🇬🇧", callback_data="lang_en"),
        )

        bot.send_message(
            message.chat.id,
            TRANSLATIONS["dr"]["choose_lang"],
            reply_markup=markup,
        )
        return

    lang = data[uid]["lang"]

    if not check_user_membership(uid):
        required_membership_message(message.chat.id, lang)
        return

    send_main_menu(message.chat.id, lang)


@bot.callback_query_handler(func=lambda call: call.data.startswith("lang_"))
def set_language_callback(call):
    uid = str(call.from_user.id)
    lang = call.data.split("_", 1)[1]

    if lang not in TRANSLATIONS:
        lang = "dr"

    data = load_data()

    if uid not in data:
        data[uid] = {"score": 0, "bots": {}}

    data[uid]["lang"] = lang
    data[uid].setdefault("score", 0)
    data[uid].setdefault("bots", {})

    save_data(data)

    bot.answer_callback_query(call.id, "✅ زبان ذخیره شد." if lang == "dr" else "✅ Language saved.")

    try:
        bot.delete_message(call.message.chat.id, call.message.message_id)
    except Exception:
        pass

    if not check_user_membership(uid):
        required_membership_message(call.message.chat.id, lang)
        return

    send_main_menu(call.message.chat.id, lang)


@bot.callback_query_handler(func=lambda call: call.data == "check_join")
def check_join_callback(call):
    uid = str(call.from_user.id)
    data = load_data()
    lang = data.get(uid, {}).get("lang") or "dr"

    if check_user_membership(uid):
        bot.answer_callback_query(
            call.id,
            "✅ عضویت تایید شد." if lang == "dr" else "✅ Membership approved.",
        )

        try:
            bot.delete_message(call.message.chat.id, call.message.message_id)
        except Exception:
            pass

        send_main_menu(call.message.chat.id, lang)
    else:
        bot.answer_callback_query(
            call.id,
            TRANSLATIONS[lang]["not_joined_alert"],
            show_alert=True,
        )


@bot.callback_query_handler(func=lambda call: call.data == "my_info")
def my_info_callback(call):
    uid = str(call.from_user.id)
    data = load_data()
    lang = data.get(uid, {}).get("lang") or "dr"

    if not check_user_membership(uid):
        bot.answer_callback_query(call.id, "❌ ابتدا عضو کانال‌ها شوید.", show_alert=True)
        return

    user_bots = data.get(uid, {}).get("bots", {})

    status = (
        f"🟢 فعال ({len(user_bots)} ربات)"
        if lang == "dr"
        else f"🟢 Running ({len(user_bots)} bots)"
    )

    ref_link = f"https://t.me/Robat_online_bot?start={uid}"

    text = TRANSLATIONS[lang]["profile"].format(
        name=call.from_user.first_name or "Unknown",
        bot_status=status,
        score=data.get(uid, {}).get("score", 0),
        uid=uid,
        link=ref_link,
    )

    bot.answer_callback_query(call.id)
    bot.send_message(
        call.message.chat.id,
        text,
        reply_markup=get_main_menu(lang),
    )


@bot.callback_query_handler(func=lambda call: call.data == "online_bot_menu")
def online_bot_callback(call):
    uid = str(call.from_user.id)
    data = load_data()
    lang = data.get(uid, {}).get("lang") or "dr"

    if not check_user_membership(uid):
        bot.answer_callback_query(call.id, "❌ ابتدا عضو کانال‌ها شوید.", show_alert=True)
        return

    markup = types.InlineKeyboardMarkup(row_width=1)

    plans = [
        ("⏱ ۲۴ ساعت — ۵۰ امتیاز", "plan_24h"),
        ("📅 ۷ روز — ۳۵۰ امتیاز", "plan_7d"),
        ("🗓 ۱۴ روز — ۷۰۰ امتیاز", "plan_14d"),
        ("🗓 ۳۰ روز — ۱۵۰۰ امتیاز", "plan_30d"),
        ("🔙 بازگشت", "back_to_menu"),
    ]

    for title, callback_data in plans:
        markup.add(
            types.InlineKeyboardButton(title, callback_data=callback_data)
        )

    bot.answer_callback_query(call.id)
    bot.send_message(
        call.message.chat.id,
        "⏳ مدت آنلاین بودن ربات را انتخاب کنید:",
        reply_markup=markup,
    )


@bot.callback_query_handler(func=lambda call: call.data.startswith("plan_"))
def select_plan_callback(call):
    uid = str(call.from_user.id)
    data = load_data()
    lang = data.get(uid, {}).get("lang") or "dr"

    duration_map = {
        "plan_24h": 24 * 3600,
        "plan_7d": 7 * 24 * 3600,
        "plan_14d": 14 * 24 * 3600,
        "plan_30d": 30 * 24 * 3600,
    }

    cost_map = {
        "plan_24h": 50,
        "plan_7d": 350,
        "plan_14d": 700,
        "plan_30d": 1500,
    }

    plan = call.data
    if plan not in duration_map:
        bot.answer_callback_query(call.id, "❌ پلن نامعتبر است.", show_alert=True)
        return

    cost = cost_map[plan]
    duration = duration_map[plan]
    score = data.get(uid, {}).get("score", 0)

    if score < cost:
        bot.answer_callback_query(
            call.id,
            f"❌ {cost} امتیاز لازم است.",
            show_alert=True,
        )
        return

    data[uid]["pending_cost"] = cost
    data[uid]["pending_duration"] = duration
    save_data(data)

    bot.answer_callback_query(call.id)

    msg = bot.send_message(
        call.message.chat.id,
        f"📂 فایل ربات خود را با پسوند .py ارسال کنید.\n\n"
        f"💰 هزینه: {cost} امتیاز\n"
        f"⏱ مدت: {duration // 3600} ساعت",
    )

    bot.register_next_step_handler(msg, handle_uploaded_document)


@bot.callback_query_handler(func=lambda call: call.data == "back_to_menu")
def back_to_menu_callback(call):
    uid = str(call.from_user.id)
    data = load_data()
    lang = data.get(uid, {}).get("lang") or "dr"

    bot.answer_callback_query(call.id)

    try:
        bot.delete_message(call.message.chat.id, call.message.message_id)
    except Exception:
        pass

    send_main_menu(call.message.chat.id, lang)


@bot.message_handler(content_types=["document"])
def handle_uploaded_document(message):
    uid = str(message.from_user.id)
    data = load_data()
    lang = data.get(uid, {}).get("lang") or "dr"

    cost = data.get(uid, {}).get("pending_cost")
    duration = data.get(uid, {}).get("pending_duration")

    if cost is None or duration is None:
        bot.reply_to(
            message,
            "❌ ابتدا یک پلن را از «آنلاین کردن ربات» انتخاب کنید.",
        )
        return

    if data.get(uid, {}).get("score", 0) < cost:
        bot.reply_to(message, "❌ امتیاز کافی نیست.")
        return

    original_name = message.document.file_name

    if not original_name.lower().endswith(".py"):
        bot.reply_to(message, "❌ فقط فایل .py قابل قبول است.")
        return

    safe_name = safe_bot_filename(original_name)
    bot_id = f"{uid}_{safe_name}"
    path = os.path.join(USER_BOTS_DIR, f"{bot_id}_bot.py")

    try:
        file_info = bot.get_file(message.document.file_id)
        content = bot.download_file(file_info.file_path)

        with open(path, "wb") as f:
            f.write(content)

        valid, error = check_code_syntax(path)

        if not valid:
            os.remove(path)
            bot.reply_to(
                message,
                f"❌ خطای Syntax در فایل شما:\n\n{error}",
            )
            return

        # Stop an older process with the same ID.
        stop_process(bot_id)

        # WARNING:
        # Running arbitrary uploaded Python code on the same server is unsafe.
        # Use a sandbox/container with strict permissions for production.
        process = subprocess.Popen(
            ["python3", path],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )

        active_user_processes[bot_id] = process

        data[uid].setdefault("bots", {})
        data[uid]["bots"][bot_id] = {
            "file_name": safe_name,
            "file_id": message.document.file_id,
            "expire_time": time.time() + duration,
        }

        data[uid]["score"] -= cost
        data[uid].pop("pending_cost", None)
        data[uid].pop("pending_duration", None)

        save_data(data)

        bot.send_message(
            message.chat.id,
            f"🚀 ربات «{safe_name}» با موفقیت اجرا شد.",
            reply_markup=get_main_menu(lang),
        )

    except Exception as e:
        if os.path.exists(path):
            try:
                os.remove(path)
            except Exception:
                pass

        bot.reply_to(message, f"❌ خطا هنگام اجرای فایل:\n{e}")


@bot.callback_query_handler(func=lambda call: call.data == "delete_bot_menu")
def delete_bot_menu_callback(call):
    uid = str(call.from_user.id)
    data = load_data()
    lang = data.get(uid, {}).get("lang") or "dr"
    bots = data.get(uid, {}).get("bots", {})

    bot.answer_callback_query(call.id)

    if not bots:
        bot.send_message(
            call.message.chat.id,
            "❌ هیچ ربات فعالی ندارید.",
            reply_markup=get_main_menu(lang),
        )
        return

    markup = types.InlineKeyboardMarkup(row_width=1)

    for bot_id, info in bots.items():
        name = info.get("file_name", bot_id)
        markup.add(
            types.InlineKeyboardButton(
                f"🗑️ {name}",
                callback_data=f"delbot:{bot_id}",
            )
        )

    markup.add(
        types.InlineKeyboardButton(
            "🔙 بازگشت",
            callback_data="back_to_menu",
        )
    )

    bot.send_message(
        call.message.chat.id,
        "🗑️ رباتی را که می‌خواهید متوقف و حذف کنید انتخاب کنید:",
        reply_markup=markup,
    )


@bot.callback_query_handler(func=lambda call: call.data.startswith("delbot:"))
def delete_bot_callback(call):
    uid = str(call.from_user.id)
    data = load_data()
    lang = data.get(uid, {}).get("lang") or "dr"

    bot_id = call.data.split(":", 1)[1]
    bots = data.get(uid, {}).get("bots", {})

    if bot_id not in bots:
        bot.answer_callback_query(call.id, "❌ ربات پیدا نشد.", show_alert=True)
        return

    stop_process(bot_id)

    path = os.path.join(USER_BOTS_DIR, f"{bot_id}_bot.py")

    if os.path.exists(path):
        try:
            os.remove(path)
        except Exception:
            pass

    name = bots[bot_id].get("file_name", bot_id)
    del bots[bot_id]
    save_data(data)

    bot.answer_callback_query(call.id, "✅ حذف شد.")
    bot.send_message(
        call.message.chat.id,
        f"🗑️ ربات «{name}» متوقف و حذف شد.",
        reply_markup=get_main_menu(lang),
    )


@bot.callback_query_handler(func=lambda call: call.data == "buy_score_menu")
def buy_score_callback(call):
    uid = str(call.from_user.id)
    data = load_data()
    lang = data.get(uid, {}).get("lang") or "dr"

    bot.answer_callback_query(call.id)

    text = (
        "🛒 خرید امتیاز\n\n"
        "۵۰ امتیاز — ۱۰۰ افغانی\n"
        "۱۰۰ امتیاز — ۲۰۰ افغانی\n\n"
        "برای خرید با پشتیبانی تماس بگیرید."
    )

    bot.send_message(
        call.message.chat.id,
        text,
        reply_markup=get_main_menu(lang),
    )


@bot.callback_query_handler(func=lambda call: call.data == "transfer_score_menu")
def transfer_score_callback(call):
    uid = str(call.from_user.id)
    data = load_data()
    lang = data.get(uid, {}).get("lang") or "dr"

    if not check_user_membership(uid):
        bot.answer_callback_query(call.id, "❌ ابتدا عضو شوید.", show_alert=True)
        return

    bot.answer_callback_query(call.id)

    msg = bot.send_message(
        call.message.chat.id,
        "📤 آیدی عددی و مقدار امتیاز را با فاصله بفرستید.\n"
        "مثال: 123456789 20",
    )

    bot.register_next_step_handler(msg, process_score_transfer)


def process_score_transfer(message):
    sender = str(message.from_user.id)
    data = load_data()

    try:
        parts = (message.text or "").split()

        if len(parts) != 2:
            bot.reply_to(message, "❌ فرمت: USER_ID SCORE")
            return

        target = parts[0]
        amount = int(parts[1])

        if not target.isdigit() or amount <= 0:
            bot.reply_to(message, "❌ آیدی و امتیاز معتبر نیست.")
            return

        if target == sender:
            bot.reply_to(message, "❌ نمی‌توانید به خودتان انتقال دهید.")
            return

        if target not in data:
            bot.reply_to(message, "❌ کاربر مقصد ثبت نشده است.")
            return

        total = amount + 5
        current = data[sender].get("score", 0)

        if current < total:
            bot.reply_to(message, f"❌ موجودی کافی نیست. نیاز: {total}")
            return

        data[sender]["score"] -= total
        data[target]["score"] = data[target].get("score", 0) + amount

        save_data(data)

        bot.reply_to(message, "✅ انتقال با موفقیت انجام شد.")

        try:
            bot.send_message(
                int(target),
                f"🎉 {amount} امتیاز به حساب شما اضافه شد.",
            )
        except Exception:
            pass

    except ValueError:
        bot.reply_to(message, "❌ مقدار امتیاز باید عدد باشد.")
    except Exception as e:
        bot.reply_to(message, f"❌ خطا: {e}")


@bot.callback_query_handler(func=lambda call: call.data == "support_btn")
def support_callback(call):
    uid = str(call.from_user.id)
    data = load_data()
    lang = data.get(uid, {}).get("lang") or "dr"

    bot.answer_callback_query(call.id)

    msg = bot.send_message(
        call.message.chat.id,
        TRANSLATIONS[lang]["support_prompt"],
    )

    bot.register_next_step_handler(msg, forward_to_support_admin)


def forward_to_support_admin(message):
    uid = str(message.from_user.id)
    data = load_data()
    lang = data.get(uid, {}).get("lang") or "dr"

    text = message.text or message.caption or "فایل/رسانه"

    for admin_id in load_admins():
        try:
            bot.send_message(
                int(admin_id),
                "📩 پیام پشتیبانی\n\n"
                f"👤 نام: {message.from_user.first_name or 'بدون نام'}\n"
                f"🆔 UserID: {uid}\n\n"
                f"💬 پیام:\n{text}\n\n"
                "برای پاسخ، روی همین پیام Reply کنید.",
            )
        except Exception:
            pass

    bot.reply_to(message, TRANSLATIONS[lang]["support_sent"])


@bot.message_handler(commands=["admin"])
def admin_panel(message):
    if not is_admin(message.from_user.id):
        return

    markup = types.InlineKeyboardMarkup(row_width=2)
    markup.add(
        types.InlineKeyboardButton(
            "📊 آمار",
            callback_data="admin_stats",
        ),
        types.InlineKeyboardButton(
            "📢 همگانی",
            callback_data="admin_broadcast",
        ),
    )

    bot.reply_to(
        message,
        "⚙️ پنل مدیریت",
        reply_markup=markup,
    )


@bot.callback_query_handler(func=lambda call: call.data == "admin_stats")
def admin_stats_callback(call):
    if not is_admin(call.from_user.id):
        return

    data = load_data()
    bot.answer_callback_query(
        call.id,
        f"👥 کاربران: {len(data)}",
        show_alert=True,
    )


@bot.callback_query_handler(func=lambda call: call.data == "admin_broadcast")
def admin_broadcast_callback(call):
    if not is_admin(call.from_user.id):
        return

    msg = bot.send_message(
        call.message.chat.id,
        "✍️ متن پیام همگانی را ارسال کنید:",
    )

    bot.register_next_step_handler(msg, perform_broadcast)


def perform_broadcast(message):
    if not is_admin(message.from_user.id):
        return

    data = load_data()
    count = 0

    for uid in data:
        try:
            bot.send_message(int(uid), message.text or "")
            count += 1
        except Exception:
            pass

    bot.reply_to(message, f"✅ پیام برای {count} کاربر ارسال شد.")


@bot.message_handler(commands=["add"])
def manage_score(message):
    if not is_admin(message.from_user.id):
        return

    args = message.text.split()

    if len(args) != 3:
        bot.reply_to(message, "/add USER_ID SCORE")
        return

    target = args[1]

    try:
        amount = int(args[2])
    except ValueError:
        bot.reply_to(message, "❌ امتیاز باید عدد باشد.")
        return

    data = load_data()

    if target not in data:
        data[target] = {
            "score": 0,
            "lang": "dr",
            "bots": {},
        }

    data[target]["score"] = data[target].get("score", 0) + amount
    save_data(data)

    bot.reply_to(
        message,
        f"✅ موجودی جدید: {data[target]['score']}",
    )


@bot.message_handler(func=lambda message: is_admin(message.from_user.id) and message.reply_to_message is not None)
def admin_reply_to_user(message):
    replied = message.reply_to_message

    if not replied.text:
        return

    target_uid = None

    for line in replied.text.splitlines():
        if "UserID:" in line:
            digits = "".join(c for c in line.split("UserID:", 1)[1] if c.isdigit())
            if digits:
                target_uid = digits
                break

    if not target_uid:
        bot.reply_to(message, "❌ UserID پیدا نشد.")
        return

    try:
        bot.send_message(
            int(target_uid),
            f"💬 پاسخ پشتیبانی:\n\n{message.text}",
        )
        bot.reply_to(message, "✅ پاسخ ارسال شد.")
    except Exception as e:
        bot.reply_to(message, f"❌ خطا: {e}")


def restore_running_bots():
    data = load_data()
    now = time.time()
    changed = False

    for uid, user_info in data.items():
        bots = user_info.get("bots", {})

        for bot_id, info in list(bots.items()):
            expire_time = info.get("expire_time", 0)

            if expire_time and now >= expire_time:
                path = os.path.join(USER_BOTS_DIR, f"{bot_id}_bot.py")

                if os.path.exists(path):
                    try:
                        os.remove(path)
                    except Exception:
                        pass

                del bots[bot_id]
                changed = True
                continue

            path = os.path.join(USER_BOTS_DIR, f"{bot_id}_bot.py")

            if os.path.exists(path):
                try:
                    process = subprocess.Popen(
                        ["python3", path],
                        stdout=subprocess.DEVNULL,
                        stderr=subprocess.DEVNULL,
                    )
                    active_user_processes[bot_id] = process
                except Exception as e:
                    print(f"Could not restart {bot_id}: {e}")

    if changed:
        save_data(data)


def main():
    print("Bot Manager is starting...")

    load_admins()

    restore_running_bots()

    checker_thread = threading.Thread(
        target=background_expiration_checker,
        daemon=True,
    )
    checker_thread.start()

    # IMPORTANT:
    # Polling and webhook cannot be active at the same time.
    try:
        bot.delete_webhook(drop_pending_updates=True)
        print("Old webhook deleted.")
    except Exception as e:
        print(f"Could not delete webhook: {e}")

    print("Starting polling...")

    bot.infinity_polling(
        skip_pending=True,
        timeout=30,
        long_polling_timeout=30,
    )


if __name__ == "__main__":
    main()
